/*
 * This file is generated by jOOQ.
 */
package eu.macphail.yutani.game.schema;


import eu.macphail.yutani.game.schema.tables.Game;
import eu.macphail.yutani.game.schema.tables.GamePlayerList;
import eu.macphail.yutani.game.schema.tables.Player;
import eu.macphail.yutani.game.schema.tables.records.GamePlayerListRecord;
import eu.macphail.yutani.game.schema.tables.records.GameRecord;
import eu.macphail.yutani.game.schema.tables.records.PlayerRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GameRecord> GAME_PK = UniqueKeys0.GAME_PK;
    public static final UniqueKey<GamePlayerListRecord> GAME_PLAYER_LIST_UN = UniqueKeys0.GAME_PLAYER_LIST_UN;
    public static final UniqueKey<PlayerRecord> PLAYER_PK = UniqueKeys0.PLAYER_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GamePlayerListRecord, GameRecord> GAME_PLAYER_LIST__GAME_PLAYER_LIST_FK = ForeignKeys0.GAME_PLAYER_LIST__GAME_PLAYER_LIST_FK;
    public static final ForeignKey<GamePlayerListRecord, PlayerRecord> GAME_PLAYER_LIST__GAME_PLAYER_LIST_FK_1 = ForeignKeys0.GAME_PLAYER_LIST__GAME_PLAYER_LIST_FK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<GameRecord> GAME_PK = Internal.createUniqueKey(Game.GAME, "game_pk", new TableField[] { Game.GAME.ID }, true);
        public static final UniqueKey<GamePlayerListRecord> GAME_PLAYER_LIST_UN = Internal.createUniqueKey(GamePlayerList.GAME_PLAYER_LIST, "game_player_list_un", new TableField[] { GamePlayerList.GAME_PLAYER_LIST.GAME_ID, GamePlayerList.GAME_PLAYER_LIST.PLAYER_ID }, true);
        public static final UniqueKey<PlayerRecord> PLAYER_PK = Internal.createUniqueKey(Player.PLAYER, "player_pk", new TableField[] { Player.PLAYER.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<GamePlayerListRecord, GameRecord> GAME_PLAYER_LIST__GAME_PLAYER_LIST_FK = Internal.createForeignKey(Keys.GAME_PK, GamePlayerList.GAME_PLAYER_LIST, "game_player_list_fk", new TableField[] { GamePlayerList.GAME_PLAYER_LIST.GAME_ID }, true);
        public static final ForeignKey<GamePlayerListRecord, PlayerRecord> GAME_PLAYER_LIST__GAME_PLAYER_LIST_FK_1 = Internal.createForeignKey(Keys.PLAYER_PK, GamePlayerList.GAME_PLAYER_LIST, "game_player_list_fk_1", new TableField[] { GamePlayerList.GAME_PLAYER_LIST.PLAYER_ID }, true);
    }
}
