/*
 * This file is generated by jOOQ.
 */
package eu.macphail.yutani.game.schema;


import eu.macphail.yutani.game.schema.tables.Game;
import eu.macphail.yutani.game.schema.tables.GamePlayerList;
import eu.macphail.yutani.game.schema.tables.Player;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>public.game_player_list</code>.
     */
    public static final GamePlayerList GAME_PLAYER_LIST = GamePlayerList.GAME_PLAYER_LIST;

    /**
     * The table <code>public.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;
}
