apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service-dev
  namespace: yutani
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    fluxcd.io/ignore: 'true'
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: frontend
              servicePort: 80
          - path: /api/?(.*)
            backend:
              serviceName: game
              servicePort: 80