/*
 * This file is generated by jOOQ.
 */
package eu.macphail.yutani.game.schema.tables.records;


import eu.macphail.yutani.game.schema.tables.Game;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record5<UUID, JSONB, OffsetDateTime, Boolean, String> {

    private static final long serialVersionUID = 1424470338;

    /**
     * Setter for <code>public.game.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.game.data</code>.
     */
    public void setData(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.game.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.game.creation_date</code>.
     */
    public void setCreationDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.game.creation_date</code>.
     */
    public OffsetDateTime getCreationDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.game.completed</code>.
     */
    public void setCompleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.game.completed</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.game.version</code>.
     */
    public void setVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.game.version</code>.
     */
    public String getVersion() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, JSONB, OffsetDateTime, Boolean, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, JSONB, OffsetDateTime, Boolean, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<JSONB> field2() {
        return Game.GAME.DATA;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Game.GAME.CREATION_DATE;
    }

    @Override
    public Field<Boolean> field4() {
        return Game.GAME.COMPLETED;
    }

    @Override
    public Field<String> field5() {
        return Game.GAME.VERSION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public JSONB component2() {
        return getData();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreationDate();
    }

    @Override
    public Boolean component4() {
        return getCompleted();
    }

    @Override
    public String component5() {
        return getVersion();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public JSONB value2() {
        return getData();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreationDate();
    }

    @Override
    public Boolean value4() {
        return getCompleted();
    }

    @Override
    public String value5() {
        return getVersion();
    }

    @Override
    public GameRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(JSONB value) {
        setData(value);
        return this;
    }

    @Override
    public GameRecord value3(OffsetDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public GameRecord value4(Boolean value) {
        setCompleted(value);
        return this;
    }

    @Override
    public GameRecord value5(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public GameRecord values(UUID value1, JSONB value2, OffsetDateTime value3, Boolean value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(UUID id, JSONB data, OffsetDateTime creationDate, Boolean completed, String version) {
        super(Game.GAME);

        set(0, id);
        set(1, data);
        set(2, creationDate);
        set(3, completed);
        set(4, version);
    }
}
