/*
 * This file is generated by jOOQ.
 */
package eu.macphail.yutani.game.schema.tables.records;


import eu.macphail.yutani.game.schema.tables.GamePlayerList;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamePlayerListRecord extends TableRecordImpl<GamePlayerListRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 579743827;

    /**
     * Setter for <code>public.game_player_list.game_id</code>.
     */
    public void setGameId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.game_player_list.game_id</code>.
     */
    public UUID getGameId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.game_player_list.player_id</code>.
     */
    public void setPlayerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.game_player_list.player_id</code>.
     */
    public String getPlayerId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return GamePlayerList.GAME_PLAYER_LIST.GAME_ID;
    }

    @Override
    public Field<String> field2() {
        return GamePlayerList.GAME_PLAYER_LIST.PLAYER_ID;
    }

    @Override
    public UUID component1() {
        return getGameId();
    }

    @Override
    public String component2() {
        return getPlayerId();
    }

    @Override
    public UUID value1() {
        return getGameId();
    }

    @Override
    public String value2() {
        return getPlayerId();
    }

    @Override
    public GamePlayerListRecord value1(UUID value) {
        setGameId(value);
        return this;
    }

    @Override
    public GamePlayerListRecord value2(String value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public GamePlayerListRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamePlayerListRecord
     */
    public GamePlayerListRecord() {
        super(GamePlayerList.GAME_PLAYER_LIST);
    }

    /**
     * Create a detached, initialised GamePlayerListRecord
     */
    public GamePlayerListRecord(UUID gameId, String playerId) {
        super(GamePlayerList.GAME_PLAYER_LIST);

        set(0, gameId);
        set(1, playerId);
    }
}
