spring:
  jmx:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://mmacphail.eu.auth0.com/
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG