name: frontend-CI

on:
  push:
    branches: [ master ]
    paths:
    - 'frontend/**'
    
jobs:
  build:
    defaults:
      run:
        working-directory: 'frontend'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mmacphail/yutani/frontend
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
